export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_ERROR = 'ADMIN_ERROR';
export const ADMIN_SUCCESS_USERS = 'ADMIN_SUCCESS_USERS'
export const ADMIN_SUCCESS_CARS = 'ADMIN_SUCCESS_CARS'
export const ADMIN_SUCCESS_BOOKING = 'ADMIN_SUCCESS_BOOKING'
export const ADMIN_UPDATE_CARS_SUCCESS = 'ADMIN_UPDATE_CARS_SUCCESS';
export const ADMIN_DELETE_CARS_SUCCESS = 'ADMIN_DELETE_CARS_SUCCESS';